project_id = "cdotfnjrhutepntflkgq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.create-payment]
verify_jwt = true

[functions.payment-webhook]
verify_jwt = false
